app/curve/locker/routes.py
from flask import current_app as app
from flask import Blueprint, render_template, redirect, url_for
# from flask_login import current_user, login_required

from flask import Response
from flask import request

from datetime import datetime as dt
import json
import plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from app.data.local_storage import pd


from app.utilities.utility import (
    format_plotly_figure,
    get_lock_diffs,
    get_now,
    get_address_profile
)
# from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
# from matplotlib.figure import Figure
# import io

from app.curve.locker.aggregators import get_ve_locker_decay_agg, get_ve_locker_agg, get_ve_locker_agg_known

from app.curve.locker.models import get_lock_diffs 

# Blueprint Configuration
curve_locker_vecrv_bp = Blueprint(
    'curve_locker_vecrv_bp', __name__,
    url_prefix='/stakedao/staked_vecrv',
    template_folder='templates',
    static_folder='static'
)



@curve_locker_vecrv_bp.route('/', methods=['GET'])
# @login_required
def index():
    df_curve_vecrv = app.config['df_curve_vecrv']
    # df_curve_vecrv_known = app.config['df_curve_vecrv_known']
    df_curve_vecrv_agg = get_ve_locker_agg(df_curve_vecrv)
    df_curve_vecrv_decay = app.config['df_curve_vecrv_decay']
    df_curve_vecrv_decay_agg = get_ve_locker_decay_agg(df_curve_vecrv_decay)


    # Filter Data
    local_df_curve_vecrv = df_curve_vecrv.sort_values('block_timestamp').groupby(['provider']).tail(1)
    # local_df_curve_vecrv = local_df_curve_vecrv.sort_values('date').groupby(['provider']).head(1)
    local_df_curve_vecrv = local_df_curve_vecrv.sort_values('locked_balance',  axis = 0, ascending = False)
    local_df_curve_vecrv = local_df_curve_vecrv[local_df_curve_vecrv['final_lock_time'] > get_now()]

    # Fancy Decay
    processed_known_decay = df_curve_vecrv_decay[
        ['known_as', 'checkpoint_timestamp', 'total_locked_balance', 'total_effective_locked_balance']].groupby([
            'checkpoint_timestamp', 'known_as',
        ]).agg(
        total_locked_balance=pd.NamedAgg(column='total_locked_balance', aggfunc=sum),
        total_effective_locked_balance=pd.NamedAgg(column='total_effective_locked_balance', aggfunc=sum),

        ).reset_index()

    # Build chart
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.update_layout(
        title=f"Curve veCRV Lock Efficiency",
        xaxis_title="Section Date",
        yaxis_title="CRV Balance",
        yaxis2_title="Efficiency",
    )
    fig = fig.add_trace(
        go.Scatter(
            x = df_curve_vecrv_decay_agg.checkpoint_timestamp,
            y = df_curve_vecrv_decay_agg.total_effective_locked_balance / df_curve_vecrv_decay_agg.total_locked_balance, 
            name = "Efficiency",
            # line_color='black',
            # line_width=3,
            # line_shape='hvh',

        ),
        secondary_y=True
    )

    fig = fig.add_trace(
        go.Scatter(
            x=df_curve_vecrv_decay_agg.checkpoint_timestamp,
            y=df_curve_vecrv_decay_agg.total_locked_balance,
            name="Locked",
            fill='tozeroy',
            # line_shape='hvh',

            # color="pool_name"
        ),
        secondary_y=False
    )
    fig = fig.add_trace(
        go.Scatter(
            x = df_curve_vecrv_decay_agg.checkpoint_timestamp,
            y = df_curve_vecrv_decay_agg.total_effective_locked_balance, 
            name = "Effectively Locked",
            fill='tozeroy',
            # line_width=3,
            # line_shape='hvh',

        ),
        # secondary_y=True
    )

    # fig.add_vline(x=dt.utcnow(), line_width=2, line_dash="dash", line_color="black" )
    fig.update_layout(autotypenumbers='convert types')

    fig.update_yaxes(range=[0,1], secondary_y=True)

    fig = format_plotly_figure(fig)
    # Build Plotly object
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)



    fig = px.line(df_curve_vecrv_agg,
                    x=df_curve_vecrv_agg['checkpoint_timestamp'],
                    y=df_curve_vecrv_agg['balance_delta'],
                    # color='known_as',
                    # line_shape='linear',
                    # facet_row=facet_row,
                    # facet_col_wrap=facet_col_wrap
                    )
    # fig.add_vline(x=dt.utcnow(), line_width=2, line_dash="dash", line_color="black")
    fig.update_layout(
        title=f"Locked vecrv Total Balance Changes",
            xaxis_title="Date",
            yaxis_title="Locked vecrv Balance Delta",
        #     legend_title="Legend Title",
        # height= 1000,
    )
    fig = format_plotly_figure(fig)
    # # Build Plotly object
    graphJSON2 = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    
    fig = px.line(processed_known_decay,
                    x=processed_known_decay['checkpoint_timestamp'],
                    y=processed_known_decay['total_effective_locked_balance'],
                    color='known_as',
                    line_shape='hv',
                    # facet_row=facet_row,
                    # facet_col_wrap=facet_col_wrap
                    )
    # fig.add_vline(x=dt.utcnow(), line_width=2, line_dash="dash", line_color="black")
    fig.update_layout(
        title=f"Curve Locked veCRV Balances",
            xaxis_title="Date",
            yaxis_title="Locked veCRV Balance",
        #     legend_title="Legend Title",
        )
    fig = format_plotly_figure(fig)

    # # Build Plotly object
    graphJSON3 = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

   # Build chart
    fig = px.bar(local_df_curve_vecrv,
                    x=local_df_curve_vecrv['final_lock_time'],
                    y=local_df_curve_vecrv['locked_balance'],
                    # color='provider',
                    title='Final Lock Time',
                    # facet_row=facet_row,
                    # facet_col_wrap=facet_col_wrap
                    )
    # fig.add_vline(x=dt.utcnow(), line_width=2, line_dash="dash", line_color="black")
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
    fig.update_layout(autotypenumbers='convert types')
    fig = format_plotly_figure(fig)        
    graphJSON4 = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)


    return render_template(
        'index_curve_locked_vecrv.jinja2',
        title='Curve - Locked veCRV - System',
        template='curve-locked-vecrv-index',
        body="",
        # sum_current_votes = df_current_votes.total_vote_power.sum(),
        # sum_prior_votes = df_prior_votes.total_vote_power.sum(),
        # convex_agg_vote_locks = df_locker_agg_system,
        # convex_agg_epoch_vote_locks_current = df_locker_agg_current,
        curve_vecrv = local_df_curve_vecrv,
        total_locked = df_curve_vecrv_decay_agg.iloc[-1]['total_locked_balance'],
        effectively_locked = df_curve_vecrv_decay_agg.iloc[-1]['total_effective_locked_balance'],
        graphJSON = graphJSON,
        graphJSON2 = graphJSON2,
        graphJSON3 = graphJSON3,
        graphJSON4 = graphJSON4

    )



@curve_locker_vecrv_bp.route('/locker/<string:user>', methods=['GET'])
# @login_required
def show(user):
    df_curve_vecrv = app.config['df_curve_vecrv']
    df_curve_vecrv_decay = app.config['df_curve_vecrv_decay']
    # df_curve_vecrv_agg = app.config['df_curve_vecrv_agg']

    
    # Filter Data
    local_df_curve_vecrv = df_curve_vecrv[df_curve_vecrv['provider'] == user]
    local_df_curve_vecrv = local_df_curve_vecrv.sort_values(['block_timestamp', 'final_lock_time'],  axis = 0, ascending = False)

    local_df_curve_vecrv_decay = df_curve_vecrv_decay[df_curve_vecrv_decay['provider'] == user]
    local_df_curve_vecrv_decay = local_df_curve_vecrv_decay.sort_values(['checkpoint_id', 'final_lock_time'],  axis = 0, ascending = False)
    # local_df_locker = df_locker[df_locker['user'] == user]

    # local_df_locker_current = local_df_locker[local_df_locker['epoch_end'] >= dt.utcnow()]

    # local_df_gauge_votes = df_all_by_gauge.groupby(['voter', 'gauge_addr'], as_index=False).last()

    # Build chart
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.update_layout(
        title=f"Curve veCRV Lock Efficiency",
        xaxis_title="Section Date",
        yaxis_title="CRV Balance",
        yaxis2_title="Efficiency",
    )
    fig = fig.add_trace(
        go.Scatter(
            x = local_df_curve_vecrv_decay.checkpoint_timestamp,
            y = local_df_curve_vecrv_decay.total_effective_locked_balance / local_df_curve_vecrv_decay.total_locked_balance, 
            name = "Efficiency",
            # line_color='black',
            # line_width=3,
            # line_shape='hvh',

        ),
        secondary_y=True
    )

    fig = fig.add_trace(
        go.Scatter(
            x=local_df_curve_vecrv_decay.checkpoint_timestamp,
            y=local_df_curve_vecrv_decay.total_locked_balance,
            name="Locked",
            fill='tozeroy',
            # line_shape='hvh',

            # color="pool_name"
        ),
        secondary_y=False
    )
    fig = fig.add_trace(
        go.Scatter(
            x = local_df_curve_vecrv_decay.checkpoint_timestamp,
            y = local_df_curve_vecrv_decay.total_effective_locked_balance, 
            name = "Effectively Locked",
            fill='tozeroy',
            # line_width=3,
            # line_shape='hvh',

        ),
        # secondary_y=True
    )

    # fig.add_vline(x=dt.utcnow(), line_width=2, line_dash="dash", line_color="black" )
    fig.update_layout(autotypenumbers='convert types')

    fig.update_yaxes(range=[0,1], secondary_y=True)

    fig = format_plotly_figure(fig)
    # Build Plotly object
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    # fig = px.bar(local_df_curve_vecrv,
    #                 x=local_df_curve_vecrv['date'],

app/curve/locker/templates/curve_locked_vecrv_decay_table_helper.jinja2
<div class="row">

    <div id='locked_vecrv_decay_table' ></div>
</div>

<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'checkpoint_id', name: 'Checkpoint ID',
            {% include 'utility_sort_int.jinja2' %} 
          },
          { id: 'checkpoint_timestamp', name: 'Checkpoint Date' },
          { id: 'known_as', name: 'Known As' },
          { id: 'provider', name: 'Staker' ,
            formatter: (_, row) => gridjs.html(
                `${row.cells[3].data.toString()}`
            )
          },
          
          { id: 'total_locked_balance', name: 'Locked CRV',
            formatter: (_, row) =>  `${row.cells[4].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
         },
        { id: 'total_effective_locked_balance', name: 'veCRV Balance',
            formatter: (_, row) =>  `${row.cells[5].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
         },
          { id: 'efficiency', name: 'Efficiency' },
          { id: 'final_lock_time', name: 'Final Lock Time' },

        ],
        data: [
          {% for index, row in curve_vecrv_decay.iterrows() %}
            {
              'checkpoint_id': '{{ row['checkpoint_id'] }}',
              'checkpoint_timestamp': '{{ row['checkpoint_timestamp'] }}',
              'known_as': '{{ row['known_as'] }}',
              'provider': `<a href={{ url_for('curve_locker_vecrv_bp.show', user = row['provider']) }}>{{row['provider']}}</a>`,

              'total_locked_balance': '{{ row['total_locked_balance']|round(2) }}',
              'total_effective_locked_balance': '{{ row['total_effective_locked_balance']|round(2) }}',
              'efficiency': '{{ row['efficiency']  }}',
              'final_lock_time': '{{ row['final_lock_time'] }}',

            },
          {% endfor %}
        ],
        {% include 'table_format_helper.jinja2' %}
  
      }).render(document.getElementById('locked_vecrv_decay_table'));
</script>

app/curve/locker/templates/curve_locked_vecrv_processed_table_helper.jinja2
<div class="row">

    <div id='locked_vecrv_table' ></div>
</div>

<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'block_timestamp', name: 'Block Timestamp' },
          { id: 'known_as', name: 'Known As' },
          { id: 'provider', name: 'Staker' ,
            formatter: (_, row) => gridjs.html(
                `${row.cells[2].data.toString()}`
            )
          },
          
          { id: 'balance_delta', name: 'Locked Delta',
            formatter: (_, row) =>  `${row.cells[3].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
         },
        { id: 'locked_balance', name: 'Locked CRV',
            formatter: (_, row) =>  `${row.cells[4].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
         },
          { id: 'event_name', name: 'Event Name' },
          { id: 'final_lock_time', name: 'Final Lock Time' },

        ],
        data: [
          {% for index, row in curve_vecrv.iterrows() %}
            {
              'block_timestamp': '{{ row['block_timestamp'] }}',
              'known_as': '{{ row['known_as'] }}',
              'provider': `<a href={{ url_for('curve_locker_vecrv_bp.show', user = row['provider']) }}>{{row['provider']}}</a>`,

              'balance_delta': '{{ row['balance_delta']|round(2) }}',
              'locked_balance': '{{ row['locked_balance']|round(2) }}',
              'event_name': '{{ row['event_name'] }}',
              'final_lock_time': '{{ row['final_lock_time'] }}',

            },
          {% endfor %}
        ],
        {% with table_type = 'secondary' %}
            {% include 'table_format_helper.jinja2' %}
        {% endwith %}
      }).render(document.getElementById('locked_vecrv_table'));
</script>

app/curve/locker/templates/curve_locked_vecrv_table_manager.jinja2
 {% block content %}


<div class ="row">

    <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" data-bs-toggle="tab" href="#lockEvents" aria-selected="true" role="tab">Lock Events</a>
    </li>

    <li class="nav-item" role="presentation">
        <a class="nav-link" data-bs-toggle="tab" href="#checkpoints" aria-selected="false" role="tab" tabindex="-1">Checkpoints</a>
    </li>


    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active show" id="lockEvents" role="tabpanel">

            {% with id="locked_vecrv_table" %}
                {% include 'curve_locked_vecrv_processed_table_helper.jinja2' %} 
            {% endwith %}
    
        </div>

        <div class="tab-pane fade" id="checkpoints" role="tabpanel">

            {% with id="locked_vecrv_decay_table" %}
                {% include 'curve_locked_vecrv_decay_table_helper.jinja2' %} 
            {% endwith %}
        </div>
    </div>

     


</div>

    {% endblock %}

app/curve/locker/templates/index_curve_locked_vecrv.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "curve" -%}
  {% set active_page = "curve_locker" -%}
  {% set sub_active_page = 'home' -%}
  {% include "navigation.jinja2" %}

    <div class="row">
      <h1>{{ title }}</h1>
    </div>

    <div class="row">

    <div class = "col-sm">
        <div class="card border-info mb-3" >
          <div class="card-header">Total CRV Locked:  </div>
          <div class="card-body">
            <h4 class="card-title text-info">{{  "{:,.2f}".format(total_locked) }}</h4>
            {# <h4 class="card-title">{{ "veCRV Balance: {:,.2f}".format(curve_vecrv['effectively_locked_balance'].sum()) }}</h4> #}

            {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
          </div>
        </div>
    </div>
      <div class = "col-sm">
        <div class="card border-primary mb-3" >
          <div class="card-header">Total veCRV Supply:  </div>
          <div class="card-body">
            <h4 class="card-title text-primary">{{ "{:,.2f}".format( effectively_locked) }} </h4>

          </div>
        </div>
    </div>
    <div class = "col-sm">

        <div class="card border-info mb-3"  >
          <div class="card-header">Current Lockers: </div>
          <div class="card-body">
            <h4 class="card-title">{{ "{:,.0f}".format(curve_vecrv.shape[0]) }}</h4>

            {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
          </div>
        </div>

    </div>
    <div class="row">

        <div class="card text-white bg-primary mb-3" style="max-width: 50%;" >
            <div class="card-header">Total veCRV Locked </div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart" class="chart"></div>

            </div>
        </div>

        <div class="card text-white bg-info mb-3" style="max-width: 50%;" >
            <div class="card-header">Final Lock Time Distribution</div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart4" class="chart4"></div>

            </div>
        </div>

    </div>

    {# {% with sum_current_votes=sum_current_votes %}
      {% with sum_prior_votes=sum_prior_votes %}
        {% include 'utility_vote_compare.jinja2' %} 
      {% endwith %}
    {% endwith %} #}



    <div class="row">
        <div class="card text-white bg-secondary mb-3" style="max-width: 50%;" >
            <div class="card-header">Daily Locked veCRV Balance Changes</div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart2" class="chart2"></div>

            </div>
        </div>

        <div class="card text-white bg-success mb-3" style="max-width: 50%;"  >
            <div class="card-header">Known Locked veCRV Balances</div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart3" class="chart3"></div>

            </div>
        </div>

    </div>


    <h4 class="text-primary">Current Locked veCRV Balances</h4>

    {# {% with df_snapshot=convex_snapshot_aggregate_votes %}
      {% with snapshot_space='convex' %}
          {% with table_tag='agg' %}
            {% include 'snapshot_table_manager.jinja2' %} 
          {% endwith %}
      {% endwith %}
    {% endwith %} #}


<div class="row">

    <div id='locked_vecrv_table' ></div>
</div>


<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script type='text/javascript'>
  var graphs = {{graphJSON | safe}};
  Plotly.plot('chart',graphs,{});
</script>

<script type='text/javascript'>
  var graphs2 = {{graphJSON2 | safe}};
  Plotly.plot('chart2',graphs2,{});
</script>

<script type='text/javascript'>
  var graphs3 = {{graphJSON3 | safe}};
  Plotly.plot('chart3',graphs3,{});
</script>

<script type='text/javascript'>
  var graphs4 = {{graphJSON4 | safe}};
  Plotly.plot('chart4',graphs4,{});
</script>


<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'block_timestamp', name: 'Block Timestamp' },
          { id: 'known_as', name: 'Known As' },
          { id: 'provider', name: 'Locker' ,
            formatter: (_, row) => gridjs.html(
                `${row.cells[2].data.toString()}`
            )
          },
          
          { id: 'balance_delta', name: 'Locked Delta',
            formatter: (_, row) =>  `${row.cells[3].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
         },
        { id: 'locked_balance', name: 'Locked CRV',
            formatter: (_, row) =>  `${row.cells[4].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
         },
          { id: 'event_name', name: 'Event Name' },
          { id: 'final_lock_time', name: 'Final Lock Time' },

        ],
        data: [
          {% for index, row in curve_vecrv.iterrows() %}
            {
              'block_timestamp': '{{ row['block_timestamp'] }}',
              'known_as': '{{ row['known_as'] }}',
              'provider': `<a href={{ url_for('curve_locker_vecrv_bp.show', user = row['provider']) }}>{{row['provider']}}</a>`,

              'balance_delta': '{{ row['balance_delta']|round(2) }}',
              'locked_balance': '{{ row['locked_balance']|round(2) }}',
              'event_name': '{{ row['event_name'] }}',
              'final_lock_time': '{{ row['final_lock_time'] }}',

            },
          {% endfor %}
        ],
        {% include 'table_format_helper.jinja2' %}
      }).render(document.getElementById('locked_vecrv_table'));
</script>



{% endblock %}

app/curve/locker/templates/index_locker.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "curve" -%}
  {% set active_page = "curve_locker" -%}
  {% set sub_active_page = 'home' -%}
  {% include "navigation.jinja2" %}

    <div class="row">
      <h1>{{ title }}</h1>
    </div>
    <div class="row">

      <div class="card border-primary mb-3" style="max-width: 50%;" >
        <div class="card-header">Total CRV Locked :  </div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.2f}".format(lockers['balance_adj'].sum()) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

      <div class="card border-secondary mb-3" style="max-width: 50%;" >
        <div class="card-header">Current Lockers : </div>
        <div class="card-body">
          <h4 class="card-title">{{ lockers.shape[0] }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

    </div>
    <div class="row">
      <div class="card text-white bg-info mb-10"  style="max-width: 50%;">
        <div class="card-header">Total CRV Locked </div>
        <div class="card-body">
            <h4 class="card-title"></h4>
            {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
            <div id="chart" class="chart"></div>

        </div>              
    </div>
    <div class="card text-white bg-primary mb-10"  style="max-width: 50%;">
      <div class="card-header">Whitelisted Lockers</div>
      <div class="card-body">
          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
          <div id="chart2" class="chart2"></div>

      </div>              
    </div>
  </div>

  <div class="row">
    <div class="card text-white bg-primary mb-10"  style="max-width: 50%;">
      <div class="card-header">Curve Locked</div>
      <div class="card-body">
          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
          <div id="chart4" class="chart4"></div>

      </div>              
    </div>

    <div class="card text-white bg-secondary mb-10"  style="max-width: 50%;">
      <div class="card-header">Whitelisted Lockers</div>
      <div class="card-body">
          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
          <div id="chart3" class="chart3"></div>

      </div>              
    </div>
  </div>
  <div class="row">

    <div id="lock_table"></div>

  </div>
<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'known_as', name: 'Known As' },
          { id: 'address', name: 'Address',
            formatter: (_, row) => gridjs.html(
              `<a href=${row.cells[6].data}>${row.cells[1].data}</a>`
            )
          },
          { id: 'balance_adj', name: 'Balance Adj',
            {# formatter: (_, row) =>  `${row.cells[2].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}` #}
          },
          { id: 'final_lock_time', name: 'Final Lock Time' },
          { id: 'timestamp', name: 'Last Locked' },
          { id: 'period', name: 'period' },
          { id: '_', 
            name: '_',
            formatter: (_, row) => gridjs.html(``)
          },
        ],
        data: [
          {% for index, row in lockers.iterrows() %}
            {
              'known_as': '{{ row['known_as'] }}',
              'address': '{{ row['provider'] }}',
              {# 'balance_adj': '{{ row['balance_adj']|round(2) }}', #}
              'balance_adj': '{{ row['balance_adj_formatted'] }}',
              'final_lock_time': '{{ row['final_lock_time'] }}',
              'timestamp': '{{ row['timestamp'] }}',
              'period': '{{ row['period'] }}',
              '_': `{{ url_for('curve_locker_vecrv_bp.show', provider = row['provider']) }}`

            },
          {% endfor %}
        ],
        fixedHeader: true,
        search: true,
        sort: true,
        pagination: {
          limit: 50,
          summary: true
        },
        className: {
          {# td: 'my-td-class', #}
          th: 'table-primary',
          table: 'table table-hover' 
        }
      }).render(document.getElementById('lock_table'));
</script>


<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>

<script type='text/javascript'>
  var graphs = {{graphJSON | safe}};
  Plotly.plot('chart',graphs,{});
</script>

<script type='text/javascript'>
  var graphs2 = {{graphJSON2 | safe}};
  Plotly.plot('chart2',graphs2,{});
</script>

<script type='text/javascript'>
  var graphs3 = {{graphJSON3 | safe}};
  Plotly.plot('chart3',graphs3,{});
</script>

<script type='text/javascript'>
  var graphs4 = {{graphJSON4 | safe}};
  Plotly.plot('chart4',graphs4,{});
</script>


{% endblock %}