app/stakedao/delegations/routes.py
from flask import current_app as app

from flask import Blueprint, render_template, redirect, url_for
# from flask_login import current_user, login_required

from flask import Response
from flask import request

from datetime import datetime as dt
import json
import plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from app.data.local_storage import pd


# from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
# from matplotlib.figure import Figure
# import io

from app.stakedao.delegations.models import get_stakedao_delegate_agg

from app.utilities.utility import (
    format_plotly_figure,
    get_now,
    get_address_profile

)

# Blueprint Configuration
stakedao_snapshot_delegations_bp = Blueprint(
    'stakedao_snapshot_delegations_bp', __name__,
    url_prefix='/stakedao/delegations',
    template_folder='templates',
    static_folder='static'
)

# df_vote_aggregates = app.config['df_stakedao_snapshot_vote_aggregates']
# df_vote_choice = app.config['df_stakedao_snapshot_vote_choice']


# proposal_end	proposal_title	choice	sum	count

@stakedao_snapshot_delegations_bp.route('/', methods=['GET'])
# @login_required
def index():

    df_stakedao_delegations = app.config['df_stakedao_delegations']
    df_stakedao_delegated_locks_per_proposal = app.config['df_stakedao_delegated_locks_per_proposal']
    df_stakedao_delegations_agg = get_stakedao_delegate_agg(df_stakedao_delegated_locks_per_proposal)
    # Filter Data


    # Build chart
    temp_df_stakedao_delegations_agg = df_stakedao_delegations_agg.sort_values(['proposal_start', 'total_delegated'], ascending = False)
    fig = px.line(temp_df_stakedao_delegations_agg, x="proposal_start", y="total_delegated", color='delegate')
    fig.update_layout(
        title=f"Delegated Balance Per Delegate",
    #     xaxis_title="X Axis Title",
    #     yaxis_title="Y Axis Title",
    #     legend_title="Legend Title",
        font=dict(
            family="Courier New, monospace",
            size=18,
            color="RebeccaPurple"
        ),
        # height= 1000,
    )
    fig = format_plotly_figure(fig)

    # Build Plotly object
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)



    temp_df_stakedao_delegations_agg = df_stakedao_delegations_agg.sort_values(['proposal_start', 'delegators_count'], ascending = False)
    fig = px.line(temp_df_stakedao_delegations_agg, x="proposal_start", y="delegators_count", color='delegate')
    fig.update_layout(
        title=f"Delegator Count Per Delegate",
    #     xaxis_title="X Axis Title",
    #     yaxis_title="Y Axis Title",
    #     legend_title="Legend Title",
        font=dict(
            family="Courier New, monospace",
            size=18,
            color="RebeccaPurple"
        ),
        # height= 1000,
    )
    fig = format_plotly_figure(fig)

    # # Build Plotly object
    graphJSON2 = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    
    return render_template(
        'index_stakedao_delegations.jinja2',
        title='StakeDAO Delegations',
        template='stakedao-delegations-index',
        body="",
        df_stakedao_delegations = df_stakedao_delegations,
        graphJSON = graphJSON,
        graphJSON2 = graphJSON2,
    )



@stakedao_snapshot_delegations_bp.route('/delegate/<string:delegate>', methods=['GET'])
def delegate(delegate):
    # df_vote_choice = app.config['df_stakedao_snapshot_vote_choice']
    df_stakedao_delegated_locks_per_proposal = app.config['df_stakedao_delegated_locks_per_proposal']
    df_stakedao_delegations_agg = app.config['df_stakedao_delegations_agg']
    df_stakedao_delegations_agg = get_stakedao_delegate_agg(df_stakedao_delegated_locks_per_proposal)

    # Filter Data

    # Aggregate Delegate
    local_df_stakedao_delegate_agg = df_stakedao_delegations_agg[df_stakedao_delegations_agg['delegate'] == delegate]
    local_df_stakedao_delegate_agg = local_df_stakedao_delegate_agg.sort_values(["proposal_start", 'total_delegated'], axis = 0, ascending = False)


    local_df_stakedao_delegated_locks_per_proposal = df_stakedao_delegated_locks_per_proposal[
        df_stakedao_delegated_locks_per_proposal['delegate'] == delegate
        ]   
    local_df_stakedao_delegated_locks_per_proposal = local_df_stakedao_delegated_locks_per_proposal.sort_values(["proposal_start", 'staked_balance'], axis = 0, ascending = False)

    local_df_current_delegate_locks = local_df_stakedao_delegated_locks_per_proposal[
        local_df_stakedao_delegated_locks_per_proposal['proposal_start'] == local_df_stakedao_delegated_locks_per_proposal.proposal_start.max()
    ]

    local_delegations = local_df_stakedao_delegated_locks_per_proposal[
            ['delegator', 'delegator_known_as', 'proposal_start', 'proposal_title', 'staked_balance']
        ].groupby(['delegator']).head(1)
    
    graph_list = []
    # Build chart

    fig = px.bar(local_df_stakedao_delegate_agg,
                    x=local_df_stakedao_delegate_agg['proposal_start'],
                    y=local_df_stakedao_delegate_agg['total_delegated'],
                    color='delegators_count',
                    title='sdCRV Delegated Power by Delegate',
                    # facet_row=facet_row,
                    # facet_col_wrap=facet_col_wrap
                    )
        # fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
    fig.update_layout(autotypenumbers='convert types')
    fig = format_plotly_figure(fig)

    # # Build Plotly object
    graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))


    # # Build chart
    fig = px.pie(local_df_current_delegate_locks, 
                values=local_df_current_delegate_locks['staked_balance'],
                names=local_df_current_delegate_locks['delegator_known_as'],
                title='Current Round Gauge Distribution',
                # hover_data=['known_as'], labels={'known_as':'known_as'}
                )
    fig.update_traces(textposition='inside', textinfo='percent')
    fig = format_plotly_figure(fig)
 
    # # Build Plotly object
    graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))

    # # Build chart
    fig = px.pie(local_df_current_delegate_locks, 
                values=local_df_current_delegate_locks['staked_balance'],
                names=local_df_current_delegate_locks['delegator'],
                title='Current Round Gauge Distribution',
                # hover_data=['known_as'], labels={'known_as':'known_as'}
                )
    fig.update_traces(textposition='inside', textinfo='percent') 
    fig = format_plotly_figure(fig)

    # # Build Plotly object
    graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))
    # # # Build chart
    # fig = px.bar(local_df_locker_user_epoch,
    #                 x=local_df_locker_user_epoch['proposal_start'],
    #                 y=local_df_locker_user_epoch['staked_balance'],
    #                 color='delegate',
    #                 title='Locked sdCRV by Delegate',
    #                 # facet_row=facet_row,
    #                 # facet_col_wrap=facet_col_wrap
    #                 )
    # fig.update_layout(autotypenumbers='convert types')
    # fig.update_yaxes(rangemode="tozero")
    # # # Build Plotly object
    # graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))



    return render_template(
        'show_stakedao_snapshot_delegate.jinja2',
        title='stakedao Delegate Lock Profile',
        template='show_stakedao_snapshot_delegate',
        body="",
        actor_profile = get_address_profile(app.config['df_roles'], delegate),
        df_locker = local_df_stakedao_delegate_agg,
        # current_votes = local_df_current_delegate_locks.iloc[0]['staked_balance'].sum(),
        local_delegations = local_delegations,
        votium_bounty_registry = app.config['votium_bounty_registry'],
        graph_list = graph_list
    )



@stakedao_snapshot_delegations_bp.route('/delegator/<string:delegator>', methods=['GET'])
def delegator(delegator):
    df_vote_choice = app.config['df_stakedao_snapshot_vote_choice']
    # df_stakedao_locker_agg_user_epoch = app.config['df_stakedao_locker_agg_user_epoch']
    df_stakedao_delegated_locks_per_proposal = app.config['df_stakedao_delegated_locks_per_proposal']

    # Filter Data
    ## Votes
    selection = [delegator]
    mask = df_vote_choice.delegators.apply(lambda x: any(item for item in selection if item in x))
    local_df_vote_choice = df_vote_choice[mask]    
    
    local_df_vote_choice = local_df_vote_choice.sort_values(["proposal_end", 'choice_power'], axis = 0, ascending = False)

    local_df_vote_choice_self_vote = df_vote_choice[
        df_vote_choice['voter'] == delegator
        ]
    
    df_vote_temp = local_df_vote_choice[
        ~local_df_vote_choice['proposal_start'].isin(local_df_vote_choice_self_vote.proposal_start.unique())
        ]
    local_df_vote_choice = pd.concat([df_vote_temp, local_df_vote_choice_self_vote])
    local_df_vote_choice = local_df_vote_choice.sort_values(['proposal_end', 'choice_power'], ascending=False)
    ## Current Votes
    max_value = local_df_vote_choice['proposal_end'].max()
    df_current_votes = local_df_vote_choice[local_df_vote_choice['proposal_end'] == max_value]

    ## Locks
    # local_df_locker_user_epoch = df_stakedao_locker_agg_user_epoch[df_stakedao_locker_agg_user_epoch['user'] == delegator]
    
    # Locks per proposal
    local_df_stakedao_delegated_locks_per_proposal = df_stakedao_delegated_locks_per_proposal[
        df_stakedao_delegated_locks_per_proposal['delegator'] == delegator
        ]
    local_df_stakedao_delegated_locks_per_proposal = local_df_stakedao_delegated_locks_per_proposal.sort_values(['proposal_start'], ascending=False)

    if not len(local_df_stakedao_delegated_locks_per_proposal) > 0:
        return render_template(

app/stakedao/delegations/templates/delegated_staked_sdcrv_not_found.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "stakedao" -%}
  {% set active_page = "stakedao_delegations" -%}
  {% set sub_active_page = 'home' -%}

  {% include "navigation.jinja2" %}
    <div class="row">
      <h1>{{ title }}</h1>
    </div>

    {% with actor_type = 'stakedao_delegator'%}
        {% with action_tag = 'Delegator'%}

        {% include 'actors_widget.jinja2' %} 
      {% endwith %}
    {% endwith %}

    <div class="row">

        <div class="card text-white bg-danger mb-3" >
          <div class="card-header">Something Went Wrong</div>
          <div class="card-body">
              <h4 class="card-title">No staked sdCRV found to delegate</h4>
              <p class="card-text">Perhaps they never got around to locking?</p>
          </div>
        </div>
    </div>

{% endblock %}

app/stakedao/delegations/templates/index_stakedao_delegations.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "stakedao" -%}
  {% set active_page = "stakedao_delegations" -%}
  {% set sub_active_page = 'home' -%}
  {% include "navigation.jinja2" %}

    <div class="row">
      <h1>{{ title }}</h1>
    </div>



  <div class="row">
    <div class="card border-primary mb-10"  >
        <div class="card-header">Delegated sdCRV</div>
        <div class="card-body">
            <h4 class="card-title"></h4>
            {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
            <div id="chart" class="chart"></div>

        </div>              
    </div>
  </div>
  <div class="row">
    <div class="card boarder-secondary mb-10"  >
      <div class="card-header">Number of Delegators</div>
      <div class="card-body">
          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
          <div id="chart2" class="chart2"></div>

      </div>              
    </div>
  </div>
  
  <div class="row">

    <div id="delegation_table"></div>

  </div>



<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'block_timestamp', name: 'Block Timestamp' },
          { id: 'event_name', name: 'Event Name' },
          { id: 'delegate', name: 'Delegate' ,
                formatter: (_, row) => gridjs.html(
                `${row.cells[2].data.toString()}`
              )
          },          { id: 'delegator', name: 'Delegator' ,
                formatter: (_, row) => gridjs.html(
                `${row.cells[3].data.toString()}`
              )
          },
          { id: 'tx_hash', name: 'Tx Hash' }

        ],
        data: [
          {% for index, row in df_stakedao_delegations.iterrows() %}
            {
              'block_timestamp': '{{ row['block_timestamp'] }}',
              'event_name': '{{ row['event_name'] }}',
              'delegate':  `<a href={{ url_for('stakedao_snapshot_delegations_bp.delegate', delegate = row['delegate']) }}>{{row['delegate']}}</a>`,

              'delegator':  `<a href={{ url_for('stakedao_snapshot_delegations_bp.delegator', delegator = row['delegator']) }}>{{row['delegator']}}</a>`,

              'tx_hash': '{{ row['tx_hash'] }}'


            },
          {% endfor %}
        ],

      {%include 'table_format_helper.jinja2' %}

      }).render(document.getElementById('delegation_table'));
</script>


<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>

<script type='text/javascript'>
  var graphs = {{graphJSON | safe}};
  Plotly.plot('chart',graphs,{});
</script>

<script type='text/javascript'>
  var graphs2 = {{graphJSON2 | safe}};
  Plotly.plot('chart2',graphs2,{});
</script>

{% endblock %}

app/stakedao/delegations/templates/show_stakedao_snapshot_delegate.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "stakedao" -%}
  {% set active_page = "stakedao_delegations" -%}
  {% set sub_active_page = 'home' -%}
  {% include "navigation.jinja2" %}

    <div class="row">
      <h1>{{ title }}</h1>
    </div>

    {% with actor_type = 'stakedao_delegate'%}
        {% with action_tag = 'Delegate'%}

        {% include 'actors_widget.jinja2' %} 
      {% endwith %}
    {% endwith %}

    <div class="row">

        <div class="card text-white bg-info mb-3" >
            <div class="card-header">Total sdCRV Locked and Delegated</div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart1" class="chart1"></div>

            </div>
        </div>
    </div>

    {# {% with sum_current_votes=sum_current_votes %}
      {% with sum_prior_votes=sum_prior_votes %}
        {% include 'utility_vote_compare.jinja2' %} 
      {% endwith %}
    {% endwith %} #}



    <div class="row">
        <div class="card text-white bg-secondary mb-3" style="max-width: 50%;" >
            <div class="card-header">Delegator Distribution By Known As</div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart2" class="chart2"></div>

            </div>
        </div>

        <div class="card text-white bg-primary mb-3" style="max-width: 50%;"  >
            <div class="card-header">Delegator Distribution By Address</div>
            <div class="card-body">
                {# <h4 class="card-title">Gauge Checkpoints By Gauge</h4> #}
                {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
                <div id="chart3" class="chart3"></div>

            </div>
        </div>

    </div>

    {# <h4 class="text-primary">Vote Locks by Epoch</h4> #}



<div class ="row">

  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" data-bs-toggle="tab" href="#aggDelegations" aria-selected="true" role="tab">Aggregate Delegations</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" data-bs-toggle="tab" href="#lastDelegations" aria-selected="false" role="tab" tabindex="-1">Unique Delegators Last Proposal</a>
    </li>
  </ul>
  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active show" id="aggDelegations" role="tabpanel">

      <div id='vote_locker_table' ></div>
    </div>
    <div class="tab-pane fade" id="lastDelegations" role="tabpanel">

      <div id='vote_locker_table2' ></div>
    </div>

  </div>

</div>

{% for graph_json in graph_list %}
    <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
    <script type='text/javascript'>
      var graphs = {{graph_json | safe}};
      Plotly.plot("chart{{loop.index}}",graphs,{});
    </script> 
{% endfor %}

<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'proposal_start', name: 'Proposal Start' },
          { id: 'proposal_title', name: 'Proposal Title' },

          { id: 'delegate_known_as', name: 'Known As' },
          { id: 'delegate', name: 'Delegate' ,
            formatter: (_, row) => gridjs.html(
                `${row.cells[3].data.toString()}`
            )
          },
          
          { id: 'total_delegated', name: 'sdCRV Delegated',
            formatter: (_, row) =>  `${row.cells[4].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,

            {% include 'utility_sort_float.jinja2' %} 
         },
        { id: 'delegators_count', name: 'Delegators Count' },
        { id: 'known_delegators', name: 'Known Delegators End' },

        ],
        data: [
          {% for index, row in df_locker.iterrows() %}
            {
              'proposal_start': '{{ row['proposal_start'] }}',
              'proposal_title': '{{ row['proposal_title'] }}',
              'delegate_known_as': '{{ row['delegate_known_as'] }}',
              'delegate': `<a href="#">{{row['delegate']}}</a>`,

              'total_delegated': '{{ row['total_delegated']|round(2) }}',
              'delegators_count': '{{ row['delegators_count'] }}',
              'known_delegators': '{{ row['known_delegators']|join(', ')  }}',

            },
          {% endfor %}
        ],
        {% include 'table_format_helper.jinja2' %}  

      }).render(document.getElementById('vote_locker_table'));
</script>


<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'proposal_start', name: 'Proposal Start' },
          { id: 'proposal_title', name: 'Proposal Title' },

          { id: 'delegator_known_as', name: 'Known As' },
          { id: 'delegator', name: 'Delegator' ,
            formatter: (_, row) => gridjs.html(
                `${row.cells[3].data.toString()}`
            )
          },
          
          { id: 'staked_balance', name: 'sdCRV Delegated',
            formatter: (_, row) =>  `${row.cells[4].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,

            {% include 'utility_sort_float.jinja2' %} 
         },

        ],
        data: [
          {% for index, row in local_delegations.iterrows() %}
            {
              'proposal_start': '{{ row['proposal_start'] }}',
              'proposal_title': '{{ row['proposal_title'] }}',
              'delegator_known_as': '{{ row['delegator_known_as'] }}',
              'delegator': `<a href="{{ url_for('stakedao_snapshot_delegations_bp.delegator', delegator= row['delegator']) }}">{{row['delegator']}}</a>`,

              'staked_balance': '{{ row['staked_balance']|round(2)}}',

            },
          {% endfor %}
        ],
        {% include 'table_format_helper.jinja2' %}  

      }).render(document.getElementById('vote_locker_table2'));
</script>


{% endblock %}
href="{{ url_for('stakedao_snapshot_delegations_bp.delegator', delegator= actor_profile['address']) }}">

app/stakedao/delegations/templates/show_stakedao_snapshot_delegator.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "stakedao" -%}
  {% set active_page = "stakedao_delegations" -%}
  {% set sub_active_page = 'home' -%}

  {% include "navigation.jinja2" %}
    <div class="row">
      <h1>{{ title }}</h1>
    </div>

    {% with actor_type = 'stakedao_delegator'%}
        {% with action_tag = 'Delegator'%}

        {% include 'actors_widget.jinja2' %} 
      {% endwith %}
    {% endwith %}



    {% with df_snapshot=df_snapshot_user %}
      {% with choice=False %}
        {% include 'snapshot_index_header.jinja2' %} 
      {% endwith %}
    {% endwith %}
    <div class="row">

        <div class="card text-white bg-info mb-3" style="max-width: 50%;">
          <div class="card-header">This Rounds Vote Distribution</div>
          <div class="card-body">
              {# <h4 class="card-title">}</h4> #}
              {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
              <div id="chart1" class="chart1"></div>
          </div>
        </div>

        <div class="card text-white bg-danger mb-3" style="max-width: 50%;" >
          <div class="card-header">sdCRV Available Per Proposal</div>
          <div class="card-body">
              {# <h4 class="card-title">}</h4> #}
              {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
              <div id="chart2" class="chart2"></div>
          </div>
        </div>
      </div>

    <div class="row">
        <div class="card text-white bg-primary mb-3"   >
          <div class="card-header">Delegated Amount Per Proposal</div>
          <div class="card-body">
              {# <h4 class="card-title">??}}</h4> #}
              {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
              <div id="chart4" class="chart4"></div>
          </div>
        </div>
      </div>

    <div class="row">

        <div class="card text-white bg-primary mb-3" >
          <div class="card-header">Delegator Vote Power by Choice</div>
          <div class="card-body">
              {# <h4 class="card-title">??}}</h4> #}
              <p class="card-text">If a Delegator votes, will report 0 Delegated Votes for that round</p>
              <div id="chart5" class="chart5"></div>
          </div>
        </div>
    </div>

    <div class="row">

      <div class="card text-white bg-danger mb-3"   >
        <div class="card-header">Delegate Vote Power by Choice</div>
        <div class="card-body">
            {# <h4 class="card-title">??}}</h4> #}
              <p class="card-text">If a Delegator votes, will report their votes instead of delegates for that round</p>
            <div id="chart3" class="chart3"></div>
        </div>
      </div>
    </div>

    <h4 class="text-primary">Delegate Votes</h4>

    {% with df_snapshot=df_snapshot_user %}
      {% with df_snapshot_adj=df_snapshot_user_adj %}
        {% with snapshot_space='stakedao' %}
            {% with table_tag='delegator' %}
              {% include 'snapshot_table_manager.jinja2' %} 
            {% endwith %}
        {% endwith %}
      {% endwith %}
    {% endwith %}


{% for graph_json in graph_list %}
    <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
    <script type='text/javascript'>
      var graphs = {{graph_json | safe}};
      Plotly.plot("chart{{loop.index}}",graphs,{});
    </script> 
{% endfor %}
{% endblock %}