app/convex/votium_bounties_v2/routes.py
from flask import current_app as app
from flask import Blueprint, render_template, redirect, url_for
# from flask_login import current_user, login_required

from flask import Response
from flask import request

from datetime import datetime
import json
import plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from app.utilities.utility import format_plotly_animation, format_plotly_figure

from .models import df_votium_v2


# Blueprint Configuration
votium_bounties_v2_bp = Blueprint(
    'votium_bounties_v2_bp', __name__,
    url_prefix='/votium_v2',
    template_folder='templates',
    static_folder='static'
)


@votium_bounties_v2_bp.route('/', methods=['GET'])
# @login_required
def index():
    # Filter Data
    df_votium_v2 = app.config['df_votium_v2']
    df = great_filter(df_votium_v2, 'index', None)

    return render_template(
        'index_votium_v2.jinja2',
        title='Votium v2 Bounties',
        template='votium-index',
        body="",
        df_votium_v2 = df['df_votium'],
        df_current = df['current'],
        df_prior = df['prior'],
        graph_list = df['graph_list'],

    )

@votium_bounties_v2_bp.route('/bounty/<string:token_addr>', methods=['GET'])
# @login_required
def show_token(token_addr):
    # Filter Data
    df_votium_v2 = app.config['df_votium_v2']
    df = great_filter(df_votium_v2, 'token', token_addr)
    
    return render_template(
        'show_token_votium_v2.jinja2',
        title='Votium v2 Bounty Token',
        template='votium-index',
        body="",
        df_votium_v2 = df['df_votium'],
        df_current = df['current'],
        df_prior = df['prior'],
        graph_list = df['graph_list'],

    )




@votium_bounties_v2_bp.route('/show/<string:gauge_addr>', methods=['GET'])
# @login_required
def show(gauge_addr):
    try:
        df_curve_gauge_registry = app.config['df_curve_gauge_registry']
    except: 
        from app.curve.gauges import df_curve_gauge_registry
    df_votium_v2 = app.config['df_votium_v2']

    # Filter Data
    # df_votium_v2

    local_df_curve_gauge_registry = df_curve_gauge_registry[
        df_curve_gauge_registry['gauge_addr'] == gauge_addr
        ]
    
    df = great_filter(df_votium_v2, 'gauge', gauge_addr)


    return render_template(
        'show_votium_v2.jinja2',
        title='Votium v2 Bounties',
        template='votium-show',
        body="",
        local_df_curve_gauge_registry = local_df_curve_gauge_registry,
        df_votium_v2 = df['df_votium'],
        df_current = df['current'],
        df_prior = df['prior'],
        graph_list = df['graph_list'],


    )






def great_filter(df, tag, target):
    if tag == 'index':
        if type(target) == list:
            pass
    elif tag == 'gauge':
        if type(target) == list:
            df = df[df['gauge_addr'].isin(target)]
        else:
            df = df[df['gauge_addr'] == target]
    elif tag == 'token':
        if type(target) == list:
            df = df[df['token'].isin(target)]
        else:
            df = df[df['token'] == target]

    # Filter Data
    graph_list = []

    if tag == 'index' or tag == 'token':
        if tag == 'index':
            # lots of gauges, less tokens
            color_target = 'token_symbol'
            alt_target = 'gauge_symbol'
        else:
            # one token, handful of gauges
            color_target = 'gauge_symbol'
            alt_target = 'token_symbol'
        """
        Bounty Value Compare Rounds
        """
        votium_rounds = df.votium_round.unique()
        votium_rounds.sort()
        current_round = votium_rounds[-1]
        prior_round = votium_rounds[-2]
        df_current_bounties = df[df['votium_round'] == current_round]
        df_prior_bounties = df[df['votium_round'] == prior_round]

        # # Build chart
        fig = px.pie(df_prior_bounties, 
                    values=df_prior_bounties['bounty_value'],
                    names=df_prior_bounties['gauge_symbol'],
                    title=f"Bounty Value by Gauge: Round {prior_round}",
                    # hover_data=['gauge_addr'], labels={'gauge_addr':'gauge_addr'}
                    )
        fig.update_traces(textposition='inside', textinfo='percent')  # percent+label
            # fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        fig.update_layout(autotypenumbers='convert types')
        fig = format_plotly_figure(fig)

        # # Build Plotly object
        graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))


        # # Build chart
        fig = px.pie(df_current_bounties, 
                    values=df_current_bounties['bounty_value'],
                    names=df_current_bounties['gauge_symbol'],
                    title=f"Bounty Value by Gauge: Round {current_round}",
                    hover_data=['gauge_addr'], labels={'gauge_addr':'gauge_addr'}
                    )
        fig.update_traces(textposition='inside', textinfo='percent')  # percent+label
            # fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        fig.update_layout(autotypenumbers='convert types')
        fig = format_plotly_figure(fig)

        # # Build Plotly object
        graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))

        """
        Animation
        """
        local_df = df.sort_values(['votium_round', 'total_vote_power', 'relative_vote_power'], ascending = False)
        fig = px.scatter(local_df, 
                    x="vecrv_per_bounty", 
                    y="relative_vote_power",
                    animation_frame="votium_round", 
                    animation_group="gauge_addr",
                    # size="bounty_value", 
                    color=color_target, 
                    hover_name=alt_target,
                    # log_x=True, 
                    # size_max=60,
                    # height=600,
                    title ="Total Vote Power vs Votes Per Dollar",
                    labels={
                            "votes_per_dollar": "Votes / Dollar",
                            "relative_vote_power": "Vote Power",
                            "token_symbol": "Bounty Token",
                            "gauge_symbol": "Gauge Symbol"
                        },
                    range_x=[50,1000],
                    range_y=[0,local_df.relative_vote_power.max()*1.1],
            )

        fig = format_plotly_figure(fig, 600)
        fig = format_plotly_animation(fig)
        # fig.layout['sliders'][0]['active'] = len(votium_rounds) - 1

        graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))

        """
        Box Compare 4 weeks back
        """
        last_x_rounds = 4
        local_df = local_df[local_df['votium_round'] >= local_df.votium_round.max()-last_x_rounds+1]
        local_df.sort_values(['bounty_value', 'votium_round', 'gauge_symbol'])
        fig = make_subplots(specs=[[{"secondary_y": True}]])
        # fig = go.Figure()
        fig.update_layout(
            title=f"Bounty (USD) vs Vote Comparison: Last {last_x_rounds} Votium Rounds",
            xaxis_title="Gauge Symbol",
            yaxis_title="Bounty Value",
            yaxis2_title='Votes (veCRV) / Bounty Value (USD)',
            height=600
        #     legend_title="Legend Title",
        )

        fig = fig.add_trace(
            go.Box(
                x=local_df[color_target],
                y=local_df.bounty_value,
                name="Bounty_Value",
                # marker_color="blue"
            ),
            secondary_y=False

        )

        fig = fig.add_trace(
            go.Box(
                x = local_df[color_target],
                y = local_df.vecrv_per_bounty, 
                name = "Votes / Bounty Value",
                marker_color="grey",

            ),
            secondary_y=True
        )

        fig.update_yaxes(rangemode='nonnegative', secondary_y=False)
        fig.update_yaxes(rangemode='tozero', secondary_y=True)
        fig.update_yaxes(range=[0,1000], secondary_y=True)
        # fig = format_plotly_figure(fig, 600)

        graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))
    

        """
        Bar Pure Vote Power And Bounties
        """

        fig = px.bar(df,
                        x=df['votium_round'],
                        y=df['relative_vote_power'],
                        color=color_target,
                        title='Relative Vote Power Per Round',
                        # facet_row=facet_row,
                        # facet_col_wrap=facet_col_wrap
                        )
        # fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        fig.update_layout(autotypenumbers='convert types')
        fig = format_plotly_figure(fig)

        # Build Plotly object
        graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))


        # # Build chart
        fig = px.bar(df,
                        x=df['votium_round'],
                        y=df['bounty_value'],
                        color=color_target,
                        title='Bounties (USD) per round',
                        # facet_row=facet_row,
                        # facet_col_wrap=facet_col_wrap
                        )
        fig = format_plotly_figure(fig)
        # # Build Plotly object 
        graph_list.append(json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder))

    
    elif tag == 'gauge':
        df_current_bounties = []
        df_prior_bounties = []
        """
        Bar Pure Vote Power And Bounties
        """
        fig = px.bar(df,
                        x=df['votium_round'],
                        y=df['relative_vote_power'],
                        color='token_symbol',
                        title='Vote Power Per Round',
                        # facet_row=facet_row,
                        # facet_col_wrap=facet_col_wrap

app/convex/votium_bounties_v2/templates/index_votium_v2.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "vote_bounties" -%}
  {% set active_page = "votium_v2" -%}
  {% set sub_active_page = 'home' -%}
  {% include "navigation.jinja2" %}

    <div class="row">
      <h1>{{ title }}</h1>
    </div>
    <div class="row">

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Current Votium Round </div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.0f}".format(df_current['votium_round'].max()) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Total Bounties Ever </div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.2f}".format(df_votium_v2['bounty_value'].sum()) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

    </div>

    <div class="row">

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Curve Checkpoint Prior: {{ "{:,.0f}".format(df_prior['checkpoint_id'].max()) }} </div>
        <div class="card-body">
          <h4 class="card-title">{{ df_prior.iloc[0]['checkpoint_timestamp'] }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Curve Checkpoint Current: {{ "{:,.0f}".format(df_current['checkpoint_id'].max()) }}</div>
        <div class="card-body">
          <h4 class="card-title">{{ df_current.iloc[0]['checkpoint_timestamp'] }}</h4>
          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

    </div>

    {% set sum_current_votes = df_current['bounty_value'].sum() %}
    {% set sum_prior_votes = df_prior['bounty_value'].sum() %}

    {# {% include 'utility_vote_compare.jinja2' %} #}
    <div class="row">
      <div class="card border-secondary mb-3" style="max-width: 50%;" >
        <div class="card-header">Total Bounties (USD) Prior Round: {{ "{:,.0f}".format(df_prior['votium_round'].max()) }}</div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.2f}".format(sum_prior_votes) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>
      <div class="card border-primary mb-3" style="max-width: 50%;" >
        <div class="card-header">Total Bounties (USD) Current Round: {{ "{:,.0f}".format(df_current['votium_round'].max()) }}</div>
        <div class="card-body">
          <li class="list-group-item d-flex justify-content-between align-items-center">

          <h4 class="card-title text-primary">{{ "{:,.2f}".format(sum_current_votes) }}</h4>
          <h4>
            {% if sum_current_votes > sum_prior_votes  %}
              <span class="badge bg-primary rounded-pill">
               + {{"{:,.2f}".format(((sum_current_votes / sum_prior_votes)-1)*100)}} %
              </span>
            {% else %}
              <span class="badge bg-secondary rounded-pill">
               {{"{:,.2f}".format(((sum_current_votes / sum_prior_votes)-1)*100)}} %
              </span>
            {% endif %}
          </h4>
          </li>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>
     </div>



    <div class="row">

        <div class="card text-white bg-secondary mb-3" style="max-width: 50%;" >
        <div class="card-header">Current Bounties</div>
        <div class="card-body">
            <div id="chart1" class="chart1"></div>

        </div>
        </div>

        <div class="card text-white bg-primary mb-3" style="max-width: 50%;">
        <div class="card-header">Prior Bounties</div>
        <div class="card-body">
            <div id="chart2" class="chart2"></div>

        </div>
        </div>
    </div>
    <div class="row">

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">By Gauge</div>
        <div class="card-body">
            <div id="chart3" class="chart3"></div>

        </div>
        </div>

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">By Bounty Token</div>
        <div class="card-body">
            <div id="chart4" class="chart4"></div>

        </div>
        </div>
    </div>

    <div class="row">

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">Vote Power</div>
        <div class="card-body">
            <div id="chart5" class="chart5"></div>

        </div>
        </div>

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">Bounty Value</div>
        <div class="card-body">
            <div id="chart6" class="chart6"></div>

        </div>
        </div>
    </div>

  <div class="row">

    <div id="bounty_table"></div>

  </div>


<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'checkpoint_id', name: 'Checkpoint ID' },
          { id: 'votium_round', name: 'Votium Round' ,
            formatter: (_, row) =>  `${row.cells[1].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_int.jinja2' %} 
          },
          { id: 'checkpoint_timestamp', name: 'Checkpoint Timestamp' },
          { id: 'gauge_symbol', name: 'Gauge Symbol',

          },
          { id: 'token_symbol', name: 'Token Symbol',
             formatter: (_, row) => gridjs.html(
                `${row.cells[4].data.toString()}`
            )
          },
          { id: 'token_amount', name: 'Token Amount' ,
            formatter: (_, row) =>  `${row.cells[5].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
          },

          { id: 'bounty_value', name: 'Bounty USD Value',
            formatter: (_, row) =>  `${row.cells[6].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
          },

          { id: 'relative_vote_power', name: 'Relative Vote Power',
            formatter: (_, row) =>  `${row.cells[7].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %}
          },

          { id: 'total_vote_power', name: 'Total Vote Power',
            formatter: (_, row) =>  `${row.cells[8].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %}
          },

          { id: 'bounty_per_vecrv', name: 'Bounty $ Per veCRV',
          {% include 'utility_sort_float.jinja2' %} 

          },

          { id: 'vecrv_per_bounty', name: 'veCRV Per Bounty $',
            formatter: (_, row) =>  `${row.cells[10].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %}
          },

          { id: 'gauge_addr', name: 'Gauge Addr',
             formatter: (_, row) => gridjs.html(
                `${row.cells[11].data.toString()}`
            )
           },


        ],
        data: [
          {% for index, row in df_votium_v2.iterrows() %}
            {
              'checkpoint_id': '{{ row['checkpoint_id'] }}',
              'votium_round': '{{ row['votium_round'] }}',

              'checkpoint_timestamp': '{{ row['checkpoint_timestamp'] }}',
              
              'gauge_symbol': '{{ row['gauge_symbol'] }}',

              'token_symbol': `<a href={{ url_for('votium_bounties_v2_bp.show_token', token_addr = row['token']) }}>{%if row['token_symbol'] %}{{row['token_symbol']}}{% else %}_{% endif %}</a>`,

              'token_amount': '{{ row['bounty_amount']|round(2) }}',

              'bounty_value': '{{ row['bounty_value']|round(2) }}',

              'relative_vote_power': '{{ row['relative_vote_power'] | round(2) }}',

              'total_vote_power': '{{ row['total_vote_power'] | round(2) }}',

              'bounty_per_vecrv': '{{ row['bounty_per_vecrv']| round(6) }}',
              'vecrv_per_bounty': '{{ row['vecrv_per_bounty'] | round(2)}}',
              
              'gauge_addr': `<a href={{ url_for('votium_bounties_v2_bp.show', gauge_addr = row['gauge_addr']) }}>{%if row['gauge_addr'] %}{{row['gauge_addr']}}{% else %}_{% endif %}</a>`,



            },
          {% endfor %}
        ],

      {%include 'table_format_helper.jinja2' %}

      }).render(document.getElementById('bounty_table'));
</script>


<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>

{% for graph_json in graph_list %}
    <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
    <script type='text/javascript'>
      var graphs = {{graph_json | safe}};
      Plotly.plot("chart{{loop.index}}",graphs,{});
    </script> 
{% endfor %}

{% endblock %}

app/convex/votium_bounties_v2/templates/show_token_votium_v2.jinja2
{% extends "layout.jinja2" %}

{#
<!-- {% block pagestyles %}
  {% assets "home_less_bundle" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
  {% endassets %}
{% endblock %} -->
#}

{% block content %}
  {% set active_category = "vote_bounties" -%}
  {% set active_page = "votium_v2" -%}
  {% set sub_active_page = 'home' -%}
  {% include "navigation.jinja2" %}

    <div class="row">
      <h1>{{ title }}</h1>
    </div>
    <div class="row">

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Current Votium Round </div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.0f}".format(df_current['votium_round'].max()) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Total Bounties Ever </div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.2f}".format(df_votium_v2['bounty_value'].sum()) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

    </div>

    <div class="row">

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Curve Checkpoint Prior: {{ "{:,.0f}".format(df_prior['checkpoint_id'].max()) }} </div>
        <div class="card-body">
          <h4 class="card-title">{{ df_prior.iloc[0]['checkpoint_timestamp'] }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

      <div class="card border-info mb-3" style="max-width: 50%;" >
        <div class="card-header">Curve Checkpoint Current: {{ "{:,.0f}".format(df_current['checkpoint_id'].max()) }}</div>
        <div class="card-body">
          <h4 class="card-title">{{ df_current.iloc[0]['checkpoint_timestamp'] }}</h4>
          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>

    </div>

    {% set sum_current_votes = df_current['bounty_value'].sum() %}
    {% set sum_prior_votes = df_prior['bounty_value'].sum() %}

    {# {% include 'utility_vote_compare.jinja2' %} #}
    <div class="row">
      <div class="card border-secondary mb-3" style="max-width: 50%;" >
        <div class="card-header">Total Bounties (USD) Prior Round: {{ "{:,.0f}".format(df_prior['votium_round'].max()) }}</div>
        <div class="card-body">
          <h4 class="card-title">{{ "{:,.2f}".format(sum_prior_votes) }}</h4>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>
      <div class="card border-primary mb-3" style="max-width: 50%;" >
        <div class="card-header">Total Bounties (USD) Current Round: {{ "{:,.0f}".format(df_current['votium_round'].max()) }}</div>
        <div class="card-body">
          <li class="list-group-item d-flex justify-content-between align-items-center">

          <h4 class="card-title text-primary">{{ "{:,.2f}".format(sum_current_votes) }}</h4>
          <h4>
            {% if sum_current_votes > sum_prior_votes  %}
              <span class="badge bg-primary rounded-pill">
               + {{"{:,.2f}".format(((sum_current_votes / sum_prior_votes)-1)*100)}} %
              </span>
            {% else %}
              <span class="badge bg-secondary rounded-pill">
               {{"{:,.2f}".format(((sum_current_votes / sum_prior_votes)-1)*100)}} %
              </span>
            {% endif %}
          </h4>
          </li>

          {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
      </div>
     </div>




    <div class="row">

        <div class="card text-white bg-secondary mb-3" style="max-width: 50%;" >
        <div class="card-header">Current Bounties</div>
        <div class="card-body">
            <div id="chart1" class="chart1"></div>

        </div>
        </div>

        <div class="card text-white bg-primary mb-3" style="max-width: 50%;">
        <div class="card-header">Prior Bounties</div>
        <div class="card-body">
            <div id="chart2" class="chart2"></div>

        </div>
        </div>
    </div>
    <div class="row">

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">By Gauge</div>
        <div class="card-body">
            <div id="chart3" class="chart3"></div>

        </div>
        </div>

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">Compare</div>
        <div class="card-body">
            <div id="chart4" class="chart4"></div>

        </div>
        </div>
    </div>

    <div class="row">

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">Vote Power</div>
        <div class="card-body">
            <div id="chart5" class="chart5"></div>

        </div>
        </div>

        <div class="card border-info mb-3" style="max-width: 50%;">
        <div class="card-header">Bounty Value</div>
        <div class="card-body">
            <div id="chart6" class="chart6"></div>

        </div>
        </div>
    </div>

  <div class="row">

    <div id="bounty_table"></div>

  </div>


<script type='text/javascript'>
      new gridjs.Grid({
        columns: [
          { id: 'checkpoint_id', name: 'Checkpoint ID' },
          { id: 'votium_round', name: 'Votium Round' ,
            formatter: (_, row) =>  `${row.cells[1].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_int.jinja2' %} 
          },
          { id: 'checkpoint_timestamp', name: 'Checkpoint Timestamp' },
          { id: 'gauge_symbol', name: 'Gauge Symbol',

          },
          { id: 'token_symbol', name: 'Token Symbol',
             formatter: (_, row) => gridjs.html(
                `${row.cells[4].data.toString()}`
            )
          },
          { id: 'token_amount', name: 'Token Amount' ,
            formatter: (_, row) =>  `${row.cells[5].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
          },

          { id: 'bounty_value', name: 'Bounty USD Value',
            formatter: (_, row) =>  `${row.cells[6].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %} 
          },

          { id: 'relative_vote_power', name: 'Relative Vote Power',
            formatter: (_, row) =>  `${row.cells[7].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %}
          },

          { id: 'total_vote_power', name: 'Total Vote Power',
            formatter: (_, row) =>  `${row.cells[8].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %}
          },

          { id: 'bounty_per_vecrv', name: 'Bounty $ Per veCRV',
          {% include 'utility_sort_float.jinja2' %} 

          },

          { id: 'vecrv_per_bounty', name: 'veCRV Per Bounty $',
            formatter: (_, row) =>  `${row.cells[10].data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`,
            {% include 'utility_sort_float.jinja2' %}
          },

          { id: 'gauge_addr', name: 'Gauge Addr',
             formatter: (_, row) => gridjs.html(
                `${row.cells[11].data.toString()}`
            )
           },


        ],
        data: [
          {% for index, row in df_votium_v2.iterrows() %}
            {
              'checkpoint_id': '{{ row['checkpoint_id'] }}',
              'votium_round': '{{ row['votium_round'] }}',

              'checkpoint_timestamp': '{{ row['checkpoint_timestamp'] }}',
              
              'gauge_symbol': '{{ row['gauge_symbol'] }}',

              'token_symbol': `<a href={{ url_for('votium_bounties_v2_bp.show_token', token_addr = row['token']) }}>{%if row['token_symbol'] %}{{row['token_symbol']}}{% else %}_{% endif %}</a>`,

              'token_amount': '{{ row['bounty_amount']|round(2) }}',

              'bounty_value': '{{ row['bounty_value']|round(2) }}',

              'relative_vote_power': '{{ row['relative_vote_power'] | round(2) }}',

              'total_vote_power': '{{ row['total_vote_power'] | round(2) }}',

              'bounty_per_vecrv': '{{ row['bounty_per_vecrv']| round(6) }}',
              'vecrv_per_bounty': '{{ row['vecrv_per_bounty'] | round(2)}}',
              
              'gauge_addr': `<a href={{ url_for('votium_bounties_v2_bp.show', gauge_addr = row['gauge_addr']) }}>{%if row['gauge_addr'] %}{{row['gauge_addr']}}{% else %}_{% endif %}</a>`,



            },
          {% endfor %}
        ],

      {%include 'table_format_helper.jinja2' %}

      }).render(document.getElementById('bounty_table'));
</script>


<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>

{% for graph_json in graph_list %}
    <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
    <script type='text/javascript'>
      var graphs = {{graph_json | safe}};
      Plotly.plot("chart{{loop.index}}",graphs,{});
    </script> 
{% endfor %}

{% endblock %}