app/curve/meta/routes.py
from flask import current_app as app
from flask import Blueprint, render_template, redirect, url_for
# from flask_login import current_user, login_required

from flask import Response
from flask import request

from datetime import datetime
import json
import plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from app.utilities.utility import pd
from .forms.power_diff_form import PowerDiffForm
from .forms.contributing_factors_form import ContributingFactorsForm, ContributingFactorsCompareForm
from app.curve.gauges.routes import get_approved
from app.utilities.utility import get_now, get_plotly_failed_chart, format_plotly_figure
from .models import get_meta, ProcessContributingFactors

# Blueprint Configuration
curve_meta_bp = Blueprint(
    'curve_meta_bp', __name__,
    url_prefix='/curve/meta',
    template_folder='templates',
    static_folder='static'
)


@curve_meta_bp.route('/', methods=['GET'])
def index():
    form = PowerDiffForm()

    this_round=0
    top_x = 20 
    compare_round=2

    df_head, df_tail = get_meta(this_round, top_x, compare_round)

    # Build chart
    fig = px.bar(df_head,
                        x=df_head.display_name,
                        y=df_head.power_difference,
                        # color=df_formated_shorts['name'],
                    title=f"Power Difference: Leader Board, Round: -{this_round}, Date: {df_head.iloc[0]['checkpoint_timestamp']}",
                    # line_shape='hvh'
                    height=600
                    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
    fig.update_layout(autotypenumbers='convert types')

    # Build Plotly object
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    # Build chart
    fig = px.bar(df_tail,
                        x=df_tail.display_name,
                        y=df_tail.power_difference,
                        # color=df_formated_shorts['name'],
                    title=f"Power Difference: Leader Board, Round: -{this_round}, Date: {df_tail.iloc[0]['checkpoint_timestamp']}",
                    # line_shape='hvh'
                    height=600
                    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
    fig.update_layout(autotypenumbers='convert types')

    # Build Plotly object
    graphJSON2 = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)


    return render_template(
        'index_curve_meta.jinja2',
        title='Curve Meta',
        template='curve-meta-show',
        body="",

        form=form,
        
        df_head = df_head,
        df_tail = df_tail,
        graphJSON = graphJSON,
        graphJSON2 = graphJSON2,
        this_round = this_round,
        top_x = top_x, 
        compare_round = compare_round
    )

@curve_meta_bp.route('/', methods=['POST'])
def custom_index():
    form = PowerDiffForm()
    if form.validate_on_submit():
        this_round= form.main_round.data if form.main_round.data else 0
        top_x = form.top_results.data
        compare_round= form.compare_round.data
    else:
        this_round=0
        top_x = 20 
        compare_round=1

    df_head, df_tail = get_meta(this_round, top_x, compare_round)

    # Build chart
    fig = px.bar(df_head,
                        x=df_head.display_name,
                        y=df_head.power_difference,
                        # color=df_formated_shorts['name'],
                    title=f"Power Difference: Leader Board, Round: -{this_round}, Date: {df_head.iloc[0]['checkpoint_timestamp']}",
                    # line_shape='hvh'
                    height=600
                    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
    fig.update_layout(autotypenumbers='convert types')

    # Build Plotly object
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    # Build chart
    fig = px.bar(df_tail,
                        x=df_tail.display_name,
                        y=df_tail.power_difference,
                        # color=df_formated_shorts['name'],
                    title=f"Power Difference: Leader Board, Round: -{this_round}, Date: {df_tail.iloc[0]['checkpoint_timestamp']}",
                    # line_shape='hvh'
                    height=600
                    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
    fig.update_layout(autotypenumbers='convert types')

    # Build Plotly object
    graphJSON2 = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)


    return render_template(
        'index_curve_meta.jinja2',
        title='Curve Meta',
        template='curve-meta-show',
        body="",

        form=form,
        
        df_head = df_head,
        df_tail = df_tail,
        graphJSON = graphJSON,
        graphJSON2 = graphJSON2,
        this_round = this_round,
        top_x = top_x, 
        compare_round = compare_round
    )


@curve_meta_bp.route('/contributing_factors', methods=['GET', 'POST'])
def contributing_factors():
    df_approved_gauges = get_approved()

    form = ContributingFactorsForm()
    if form.validate_on_submit():
        target_gauge= form.target_gauge.data if form.target_gauge.data else None
        compare_back = form.compare_back.data if form.compare_back.data else 16
    else:
        target_gauge=None
        compare_back=16
    form.process(data={'target_gauge': target_gauge, 
                       'compare_back':compare_back, 
                       })
    if not target_gauge:
        return render_template(
            'contributing_factors.jinja2',
            title='Curve Meta: Contributing Factors',
            template='contributing_factors',
            body="",
            form=form,
            df_approved_gauges = df_approved_gauges
            )
    
    pcf = ProcessContributingFactors()
    df = pcf.process_all(target_gauge, compare_back)

    if len(df) == 0:
        return render_template(
            'contributing_factors.jinja2',
            title='Curve Meta: Contributing Factors',
            template='contributing_factors',
            body="No votes found for gauge provided",
            form=form,
            df_approved_gauges = df_approved_gauges
            )
    
    df_curve_gauge_registry = app.config['df_curve_gauge_registry']
    local_df_curve_gauge_registry = df_curve_gauge_registry[df_curve_gauge_registry['gauge_addr'] == target_gauge]

    graph_list = get_contributing_factors_graphs(df)

    return render_template(
        'contributing_factors.jinja2',
        title='Curve Meta: Contributing Factors',
        template='curve-meta-show',
        body="",

        form=form,
        local_df_curve_gauge_registry = local_df_curve_gauge_registry,
        graph_list = graph_list,
        df = df,
        df_approved_gauges = df_approved_gauges

    )

@curve_meta_bp.route('/contributing_factors/<string:gauge_addr>', methods=['GET'])
def contributing_factors_show(gauge_addr):
    df_approved_gauges = get_approved()
    target_gauge = gauge_addr
    compare_back = 16
    
    form = ContributingFactorsForm()
    form.process(data={'target_gauge': target_gauge, 
                       'compare_back':compare_back, 
                       })
    
    pcf = ProcessContributingFactors()
    df = pcf.process_all(target_gauge, compare_back)

    if len(df) == 0:
        return render_template(
            'contributing_factors.jinja2',
            title='Curve Meta: Contributing Factors',
            template='contributing_factors',
            body="No votes found for gauge provided",
            form=form,
            df_approved_gauges = df_approved_gauges
            )
    
    df_curve_gauge_registry = app.config['df_curve_gauge_registry']
    local_df_curve_gauge_registry = df_curve_gauge_registry[df_curve_gauge_registry['gauge_addr'] == target_gauge]

    graph_list = get_contributing_factors_graphs(df)

    return render_template(
        'contributing_factors.jinja2',
        title='Curve Meta: Contributing Factors',
        template='curve-meta-show',
        body="",

        form=form,
        local_df_curve_gauge_registry = local_df_curve_gauge_registry,
        graph_list = graph_list,
        df = df,
        df_approved_gauges = df_approved_gauges

    )

@curve_meta_bp.route('/compare_gauges', methods=['GET', 'POST'])
def compare_gauges():
    df_approved_gauges = get_approved()

    form = ContributingFactorsCompareForm()
    if form.validate_on_submit():
        target_gauges= form.target_gauges.data if form.target_gauges.data else None
        compare_back = form.compare_back.data if form.compare_back.data else 16
        target_gauges = format_input_to_list(target_gauges)

    else:
        target_gauges=None
        compare_back=16
    form.process(data={'target_gauges': target_gauges, 
                       'compare_back':compare_back, 
                       })
    if not target_gauges:
        return render_template(
            'contributing_factors_compare.jinja2',
            title='Curve Meta: Contributing Factors',
            template='contributing_factors',
            body="",
            form=form,
            df_approved_gauges = df_approved_gauges
            )
    
    pcf = ProcessContributingFactors()
    df = pcf.process_all(target_gauges, compare_back)

    if len(df) == 0:
        return render_template(
            'contributing_factors_compare.jinja2',
            title='Curve Meta: Contributing Factors',
            template='contributing_factors',
            body="No votes found for at least one gauge provided",
            form=form,
            df_approved_gauges = df_approved_gauges
            )
    
    df_curve_gauge_registry = app.config['df_curve_gauge_registry']
    local_df_curve_gauge_registry = df_curve_gauge_registry[df_curve_gauge_registry['gauge_addr'].isin(target_gauges)]

    graph_list = generate_plot_per_gauge(df)

app/home/routes.py
import os
from datetime import datetime as dt

from flask import current_app as app
from flask import Blueprint, render_template, redirect, url_for
# from flask_login import current_user, login_required

from app.home.content.nerd_stuff import nerd_stuff
from app.home.content.to_do import to_do

from app.data.reference import core_filename_list

from .forms import EntryForm
# from app.data.data_manager import Manager
# from .forms import DataManagerForm


# Blueprint Configuration

home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates',
    static_folder='static'
    )

# Controller info
@home_bp.route('/', methods=['GET', 'POST'])
def home():
    """Homepage."""
    # Bypass if user is logged in

    form = EntryForm()
    if form.validate_on_submit():
        search_target = form.search_target.data.lower() if form.search_target.data else None
        return redirect(url_for('address_book_bp.search', search_target=search_target))

    return render_template(
        'index.jinja2',
        title='The Center For Llamas who want to Curve good',
        subtitle='and learn to do governance stuff good too.',
        template='home-template',
        nerd_stuff = nerd_stuff,
        to_do = to_do,
        form=form,

    )


 


# @home_bp.route('/data/male_models', methods=['GET','POST'])
# def male_models():
#     """Data Management in site."""
#     # Bypass if user is logged in
#     form = DataManagerForm()
#     manager_config = {
#         # Curve
#         'gauge_to_lp_map': False,
#         'curve_locker': False,
#         'curve_gauge_votes': False,
#         'curve_gauge_rounds': False,
        
#         'curve_liquidity': False, 
        
#         # Convex
#         'convex_snapshot_curve': False,
#         'convex_locker': False,
#         'convex_delegations': False,

#         # StakeDAO
#         'stakedao_snapshot_curve': False,
#         'stakedao_staked_sdcrv': False,
#         'stakedao_locker': False,
#         'stakedao_delegations': False,


#         #Votium
#         'votium_bounties_v2': False,
#         'votium_bounties_v1': False,

#         # Warden
#         'warden_vesdt_boost_delegation': False,

#         # Address Book
#         'address_book_actors': False,
#     }
#     placeholder_list = []
#     for key in manager_config.keys():
#         placeholder_list.append({ 'component_name': key,'run_component': False})
   
#     if form.validate_on_submit():
#         load_initial= form.load_initial.data if form.load_initial.data else False
#         should_fetch = form.should_fetch.data if form.should_fetch.data else False
#         should_process = form.should_process.data if form.should_process.data else False
#         load_cutoff  = form.load_cutoff.data if form.load_cutoff.data else False
#         # config = form.manager_config.data if form.manager_config.data else placeholder_list
#         mc = {}
#         config = []
#         i = 0
#         for entry in form.manager_config.data:
#             mc[placeholder_list[i]['component_name']] = entry['run_component'] 
#             config.append({'component_name': placeholder_list[i]['component_name'], 'run_component': entry['run_component']})
#             i += 1
#         manager = Manager(
#             mc, 
#             should_fetch, 
#             should_process,
#             load_initial,
#             # Liquidity Specific
#             load_cutoff,
#             )
#         manager.manage()
#     else:
#         load_initial = False
#         should_fetch = False
#         should_process = False
#         load_cutoff = False
#         config = placeholder_list

#     form.process(data={
#         'load_initial': load_initial, 
#         'should_fetch':should_fetch, 
#         'should_process':should_process, 

#         'load_cutoff': load_cutoff, 
#         'manager_config':config,
#         })
    

#     file_info = generate_file_info()
#     return render_template(
#         'data_manager.jinja2',
#         title='The Center For Llamas who want to Curve good',
#         subtitle='and learn to do governance stuff good too.',
#         template='home-template',
#         form=form,
#         file_info = file_info
#     )




# def generate_file_info(is_alt_path=False):
#     file_info = {}
#     now_time = dt.now()
#     found_count = 0
#     for file in core_filename_list:
#         file_info[file] = {'last_modified': None, 'days': -1}
#         for path in [RAW_FOLDER_PATH]:
#             try:
#                 if is_alt_path:
#                     prefix = 'center-for-llamas/'
#                 else:
#                     prefix = ''
#                 date = dt.fromtimestamp(os.path.getmtime(f"{prefix}app/data/{path}/{file}.csv"))
#                 file_info[file]['last_modified'] = date
#                 file_info[file]['days'] = (now_time - date).days

#                 found_count+=1
#             except:
#                 pass
#                 # print(f"\t\tno file found for {file}")
#     if found_count == 0 and not is_alt_path:
#         return generate_file_info(True)
#     return file_info

app/templates/actors_widget.jinja2
{% set actor_profile = actor_profile|default([]) -%}

{%if actor_profile |length > 0 %}

   
{# {% set actor_type = 'curve_vecrv_locker' -%} #}
{% set actor_type = actor_type|default("curve_vecrv_locker") -%}
{% set action_tag = action_tag|default("User") -%}

{% set actor_profile = actor_profile.iloc[0] -%}

<div class="row">
    <div class="col-md">
    <div class="card border-primary mb-3"  >
        <div class="card-header">{{action_tag}}</div>
        <div class="card-body">
        <h4 class="card-title">{{actor_profile['address']}}</h4>
        <a href="{{ url_for('curve_meta_bp.compare_voter', target_voter= actor_profile['address']) }}">
        <button type="button" class="btn btn-outline-dark">Compare Gauges Voted</button>
        </a>
        </div>
    </div>

    <div class="card border-secondary mb-3" >
        <div class="card-header">Known As</div>
        <div class="card-body">
        <h4 class="card-title text-primary">{{actor_profile['known_as']}}</h4>

        {# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> #}
        </div>
        

    </div>
    </div>
    <div class="col-md">


            <div class="card mb-3" style=" display:grid" >
                <div class="card-header bg-primary text-white">Curve Roles</div>
                <div class="card-body">
                    <div class ="tabbable Curve border-primary">
                        <ul class="nav nav-tabs">
                        {% for key in actor_profile.keys() %}
                            {% if actor_profile[key] == True %}


                                {% if key == "curve_vecrv_locker" %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-primary text-white  {% endif%}" 
                                    href="{{ url_for('curve_locker_vecrv_bp.show', user= actor_profile['address']) }}">
                                    veCRV Locker</a>
                                </li>
                                {% elif key == "curve_voters" %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-primary text-white  {% endif%}" 
                                    href="{{ url_for('gauge_votes_bp.show', user= actor_profile['address']) }}">
                                    veCRV Voter</a>
                                </li>

                                {% endif %}
                            {% endif %}

                        {% endfor %} 
                        </ul>


                    </div>
                </div>

                <div class="card-header bg-secondary text-white">Convex Roles</div>
                <div class="card-body">
                    <div class ="tabbable Convex border-secondary">
                        <ul class="nav nav-tabs">
                        {% for key in actor_profile.keys() %}
                            {% if actor_profile[key] == True %}

                                {% if key == 'convex_snapshot_voter' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-secondary text-white {% endif%}" 
                                    href="{{ url_for('convex_snapshot_bp.voter', voter= actor_profile['address']) }}">
                                    vlCVX Curve Snaphot Voter</a>
                                </li>
                                {% elif key == 'convex_vlcvx_locker' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-secondary text-white  {% endif%}" 
                                    href="{{ url_for('convex_vote_locker_bp.show', user= actor_profile['address']) }}">
                                    vlCVX Locker</a>
                                </li>
                                {% elif key == 'convex_delegator' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-secondary text-white  {% endif%}" 
                                    href="{{ url_for('convex_snapshot_delegations_bp.delegator', delegator= actor_profile['address']) }}">
                                    vlCVX Delegator</a>
                                </li>
                                {% elif key == 'convex_delegate' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-secondary text-white  {% endif%}" 
                                    href="{{ url_for('convex_snapshot_delegations_bp.delegate', delegate= actor_profile['address']) }}">
                                    vlCVX Delegate</a>
                                </li>
                                {% endif %}

                            {% endif %}

                        {% endfor %} 
                        </ul>

                    </div>

                </div>



                <div class="card-header bg-info text-white">StakeDAO Roles</div>
                <div class="card-body">
                    <div class ="tabbable StakeDAO border-info">
                        <ul class="nav nav-tabs">
                        {% for key in actor_profile.keys() %}
                            {% if actor_profile[key] == True %}

                                {% if key == 'stakedao_snapshot_voter' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-info text-white  {% endif%}" 
                                    href="{{ url_for('stakedao_snapshot_bp.voter', voter= actor_profile['address']) }}">
                                    sdCRV Curve Snapshot Voter</a>
                                </li>
                                {% elif key == 'stakedao_sdcrv_staker' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-info text-white  {% endif%}" 
                                    href="{{ url_for('stakedao_staked_sdcrv_bp.show', user= actor_profile['address']) }}">
                                    sdCRV Staker</a>
                                </li>
                                {% elif key == 'stakedao_vesdt_locker' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-info text-white  {% endif%}" 
                                    href="{{ url_for('stakedao_locked_vesdt_bp.show', user= actor_profile['address']) }}">
                                    veSDT Locker</a>
                                </li>
                                {% elif key == 'stakedao_delegator' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-info text-white {% endif%}" 
                                    href="{{ url_for('stakedao_snapshot_delegations_bp.delegator', delegator= actor_profile['address']) }}">
                                    sdCRV Delegator</a>
                                </li>
                                {% elif key == 'stakedao_delegate' %}
                                <li class="nav-item">
                                <a class="nav-link {% if key == actor_type %} active bg-info text-white {% endif%}" 
                                    href="{{ url_for('stakedao_snapshot_delegations_bp.delegate', delegate= actor_profile['address']) }}">
                                    sdCRV Delegate</a>
                                </li>
                                {% endif %}
                            {% endif %}

                        {% endfor %} 
                        </ul>

                    </div>

                </div>

            </div>
    </div>
    
    
</div>

{% else %}
    <div class ="row">
        <div class="card border-info mb-3"  >
            <div class="card-header">Something went wrong</div>
            <div class="card-body">
                <h4 class="card-title text-info">
                    Unable to link Actor Mapping
                </h4>

                <p class="card-text">Its likely that the data is present but the link could not be made.</p>
                <p>{{actor_profile}}</p>
            </div>
        </div>   
    </div>
    </div>
{% endif %}

app/templates/blueprintinfo.jinja2
<div class="blueprint-info">
    <h3>Blueprint Info</h3>
    <ul class="page-properties">
      <li><span class="attribute-title">Blueprint:</span> <span class="attribute-value">{{ request.blueprint }}</span></li>
      <li><span class="attribute-title">Template:</span> <span class="attribute-value">{{ self._TemplateReference__context.name }}</span></li>
      <li><span class="attribute-title">View:</span> <span class="attribute-value">{{ request.endpoint }}</span></li>
      <li><span class="attribute-title">Route:</span> <span class="attribute-value">{{ request.path }}</span></li>
    </ul>
  </div>

app/templates/generalform.jinja2
{% extends "layout.jinja2" %}


{% block content %}
  {% include "navigation.jinja2" %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button
          type="button"
          class="close"
          data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>{{ title }}</h1>

    <form method="POST" action="{{ url_for(request.endpoint) }}">
      {{ form.csrf_token }}
      {% for field in form %}
        {% if field.type != "SubmitField" and field.type != "csrf_token" %}

          <div class="form-group">
          <fieldset class="form-field">
            {{ field.label }}
            {{ field() }}
            {% if field.name.errors %}
              <ul class="errors">
                {% for error in field.name.errors %}
                  <li>{{ error }}</li>{% endfor %}
              </ul>
            {% endif %}
          </fieldset>
          </div>
        {% endif %}
      {% endfor %}
      <div class=class="btn btn-success">
        {{ form.submit }}
      </div>

    </form>

  </div>

{% endblock %}

app/templates/navigation0.jinja2
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('home_bp.home') }}">The Center For Llamas Who Want To Curve Good</a>
  </div>
  <div class="d-flex">
      <a class="nav-link active" href="https://register.app">
        <span class="badge bg-danger"><3</span>Reserve
      <span class="visually-hidden">(current)</span>
    </a>
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('curve_meta_bp.index') }}">Curve</a>
      <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li>
        <a class="nav-link active" href="{{ url_for('gauges_bp.index') }}">Gauges
          <span class="visually-hidden">(current)</span>
        </a>
        </li>

        <li>
        <a class="nav-link active" href="{{ url_for('curve_locker_vecrv_bp.index') }}">Locker
          <span class="visually-hidden">(current)</span>
        </a>
        </li>

        <li>
        <a class="nav-link active" href="{{ url_for('gauge_votes_bp.index') }}">Gauge Votes
          <span class="visually-hidden">(current)</span>
        </a>
        </li>

        <li>
        <a class="nav-link active" href="{{ url_for('gauge_checkpoints_bp.index') }}">Gauge Checkpoints
          <span class="visually-hidden">(current)</span>
        </a>
        </li>

        <li>
        <a class="nav-link active" href="{{ url_for('curve_liquidity_bp.index') }}">Liquidity
          <span class="visually-hidden">(current)</span>
        </a>
        </li>

        </ul>
        <div class="d-flex">
            <a class="nav-link active" href="">StakeDAO Bounties
            <span class="visually-hidden">(current)</span>
          </a>
        </div>

        {# <!-- <a href="{{ url_for('home_bp.home') }}">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
        </a> -->

          <!-- <a href="{{ url_for('transaction_bp.index') }}">Transactions</a>
          <a href="{{ url_for('transfer_bp.index') }}">Transfers</a> --> #}

        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="">Convex</a>
      <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        {# <li>
          <a class="nav-link active" href="{{ url_for('curve_locker_vecrv_bp.index') }}">Vote Locker
            <span class="visually-hidden">(current)</span>
          </a>
        </li> #}
        <li>
          <a class="nav-link active" href="{{ url_for('convex_snapshot_bp.index') }}">Snapshot
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li>
          <a class="nav-link active" href="{{ url_for('convex_vote_locker_bp.index') }}">Vote Locker
            <span class="visually-hidden">(current)</span>
          </a>
        </li>

        {# <li>
          <a class="nav-link active" href="">Delegations
            <span class="visually-hidden">(current)</span>
          </a>
        </li> #}
        </ul>
        <div class="d-flex">
            <a class="nav-link active" href="{{ url_for('votium_bounties_bp.index') }}">Votium Bounties
            <span class="visually-hidden">(current)</span>
          </a>
        </div>

        {# <!-- <a href="{{ url_for('home_bp.home') }}">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
        </a> -->

          <!-- <a href="{{ url_for('transaction_bp.index') }}">Transactions</a>
          <a href="{{ url_for('transfer_bp.index') }}">Transfers</a> --> #}

        </div>
    </div>
</nav>


<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="">StakeDAO</a>
      <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        {# <li>
          <a class="nav-link active" href="{{ url_for('curve_locker_vecrv_bp.index') }}">Vote Locker
            <span class="visually-hidden">(current)</span>
          </a>
        </li> #}
        <li>
          <a class="nav-link active" href="{{ url_for('stakedao_snapshot_bp.index') }}">Snapshot
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li>
          <a class="nav-link active" href="{{ url_for('stakedao_locked_vesdt_bp.index') }}">veSDT Locker
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li>
          <a class="nav-link active" href="{{ url_for('stakedao_staked_sdcrv_bp.index') }}">Staked sdCRV
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        {# <li>
          <a class="nav-link active" href="">Delegations
            <span class="visually-hidden">(current)</span>
          </a>
        </li> #}
        </ul>

        {# <!-- <a href="{{ url_for('home_bp.home') }}">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
        </a> -->

          <!-- <a href="{{ url_for('transaction_bp.index') }}">Transactions</a>
          <a href="{{ url_for('transfer_bp.index') }}">Transfers</a> --> #}

        </div>
    </div>
</nav>

app/templates/navigationauth.jinja2
<nav class="navigation-default">
  <div class="nav-wrapper">

    <div class="left-nav">
      {#
      <!-- <a href="{{ url_for('home_bp.home') }}">
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
      </a> -->
      #}
        <a href="{{ url_for('home_bp.home') }}">Home</a>
      {#
        <!-- <a href="{{ url_for('home_bp.about') }}">About</a>
        <a href="{{ url_for('home_bp.contact') }}">Contact</a> -->
      #}
    </div>



  </div>
</nav>